spring:
  profiles:
    active: default
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 11111111
    url: jdbc:mysql://localhost:3306/wiki?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: smjeon
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true